// Code generated by go-bindata.
// sources:
// text/itsyouonline.pub
// text/logo.txt
// DO NOT EDIT!

package assets

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _textItsyouonlinePub = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x5c\xce\xcd\x72\x82\x30\x14\x40\xe1\x3d\x4f\xe1\xde\xe9\x98\x32\x46\x61\xc9\xcf\x8d\xb9\x4d\x71\xea\x40\x29\xb7\x3b\x06\x52\x04\x9d\xa4\x5a\x2b\xc6\xa7\xef\x94\xa5\x67\x79\x56\xdf\xd3\x7f\x31\x6c\x70\x3b\x7b\x7b\x8f\x5f\x31\x99\x29\xa0\x69\x7a\x99\xa4\x11\x22\x92\xca\x7e\xe2\x7d\x60\x49\xb4\x23\xa1\x96\x00\x51\x82\x29\x75\x11\xe4\xbc\x0a\xaa\xf3\x97\x6a\x6f\x61\x47\xb5\x13\x58\x34\x41\x38\xd6\xed\xf2\xf7\xe7\x7c\x60\xc6\xf7\xd6\xd9\xd0\x6f\xe8\x7a\xaa\x8f\xfd\x5d\xe7\x1f\x85\x84\x6f\xd3\xae\xad\xae\x43\xdc\x05\x05\xb7\x2f\x43\x56\x4a\xde\x34\x4c\xf2\x8b\xc8\x55\x7f\x14\x42\xef\x17\x8b\xd1\x74\x37\x74\xc6\xad\xbc\xd5\xbc\x3c\xf1\x0b\x8f\x59\xc9\x60\xef\xd8\xf3\xdc\x6f\x34\x58\xe3\x13\xab\xd2\x03\xaa\xab\x37\x41\x61\x9b\x3e\xda\xff\x02\x00\x00\xff\xff\x2d\x3b\x29\xc7\xd6\x00\x00\x00")

func textItsyouonlinePubBytes() ([]byte, error) {
	return bindataRead(
		_textItsyouonlinePub,
		"text/itsyouonline.pub",
	)
}

func textItsyouonlinePub() (*asset, error) {
	bytes, err := textItsyouonlinePubBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "text/itsyouonline.pub", size: 214, mode: os.FileMode(420), modTime: time.Unix(1497264868, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _textLogoTxt = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x3c\x8a\xb1\x0d\xc0\x30\x0c\xc3\xf6\x5c\xc1\xad\xed\xe4\x87\x0c\xf0\x11\x1d\x5f\xb8\x09\xaa\x41\xb4\x09\x81\x3b\xc8\x94\x32\xf9\xa8\x2e\x22\x14\xd2\x5c\xba\x8f\x23\x0a\xcd\x9a\xa7\x66\x5b\x84\x70\xfb\xfc\x6c\xa5\x17\xa5\xb6\x1a\xc3\x38\x8b\xc3\x4c\xbd\x01\x00\x00\xff\xff\x46\x68\x46\x10\x82\x00\x00\x00")

func textLogoTxtBytes() ([]byte, error) {
	return bindataRead(
		_textLogoTxt,
		"text/logo.txt",
	)
}

func textLogoTxt() (*asset, error) {
	bytes, err := textLogoTxtBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "text/logo.txt", size: 130, mode: os.FileMode(420), modTime: time.Unix(1496749602, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"text/itsyouonline.pub": textItsyouonlinePub,
	"text/logo.txt": textLogoTxt,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"text": &bintree{nil, map[string]*bintree{
		"itsyouonline.pub": &bintree{textItsyouonlinePub, map[string]*bintree{}},
		"logo.txt": &bintree{textLogoTxt, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

